import React from "react"
import Head from "next/head"
import Navbar from "./navbar"

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>My Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="content">
				<Navbar />
				{children}
			</div>
		</>
	)
}

export default Layout
